[package]
name = "rust-dia-001"
version = "0.1.0"
edition = "2024"

## Aprendi a adicionar modulos e definir as versões usadas.
[dependencies]
regex = "1.11.1"
itertools = { version = "0.14.0" }
rayon = "1.10.0"